In [1]:
import pandas as pd ; import numpy as np; import random as rnd ;import math
#importing data visualization packages
import seaborn as sns ; import matplotlib.pyplot as plt
%matplotlib inline
#importing machine learning packages
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import Imputer
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from IPython.display import display, Math, Latex
import os; import warnings
warnings.filterwarnings("ignore",category=DeprecationWarning)
from sklearn.exceptions import DataConversionWarning
warnings.filterwarnings(action='ignore', category=DataConversionWarning)
from sklearn.ensemble import RandomForestClassifier

import warnings
from colorama import Fore, Back, Style 
import pandas as pd
import os
import numpy as np
import scattertext as st
import seaborn as sns
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
#import sys                                                    #Causes problems with regression in skikitlearn 
#reload(sys)                                                   #later on. Find different way to make Count Vectorizer
#sys.setdefaultencoding('utf8')                                #work. In future be carefull making global changes
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cross_validation import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.linear_model import ARDRegression
from sklearn.ensemble import BaggingRegressor
from scipy.cluster.hierarchy import dendrogram, linkage

import matplotlib.pyplot as plt

C:\Users\jmvig\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
!pip install scattertext

distributed 1.21.8 requires msgpack, which is not installed.
You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


## predic_13_chgenro - data2013_y1 - random forest

In [3]:
data2013_y1 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2013_y1.csv")
data2013_y1.head(3)
data2013_y1.shape
pred2013_y1 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_13y1.csv")
pred2013_y1.head(3)
pred2013_y1.shape
xtrainy1=pd.DataFrame(data2013_y1.values[:,1:27])
xtesty1=pd.DataFrame(pred2013_y1.values[:,1:27])
ytrainy1=pd.DataFrame(data2013_y1.values[:,27])
ytesty1=pd.DataFrame(pred2013_y1.values[:,27])
rfr = RandomForestRegressor().fit(xtrainy1, ytrainy1)
y_mody1=rfr.predict(xtesty1)
y_mody1
#y_mody1=pd.DataFrame(y_mody1)
#y_mody1.to_csv('pred13_y1.csv', index=False, header=False)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

## predic_13_Fracdeg - data2013_y2 - random forest

In [2]:
data2013_y2 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2013_y2.csv")
data2013_y2.head(3)
data2013_y2.shape
pred2013_y2 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_13y2.csv")
pred2013_y2.head(3)
pred2013_y2.shape
xtrainy2=pd.DataFrame(data2013_y2.values[:,1:27])
xtesy2=pd.DataFrame(pred2013_y2.values[:,1:27])
ytrainy2=pd.DataFrame(data2013_y2.values[:,27])
ytesty2=pd.DataFrame(pred2013_y2.values[:,27])
rfr = RandomForestRegressor().fit(xtrainy2, ytrainy2)
y_mody2=rfr.predict(xtesy2)
y_mody2
#y_mody2=pd.DataFrame(y_mody2)
#y_mody2.to_csv('pred13_y2.csv', index=False, header=False)

array([0.19867122, 0.13957749, 0.14947818, 0.18784815, 0.15789508,
       0.35092555, 0.2185944 , 0.19570669, 0.1995777 , 0.17574816,
       0.26931017, 0.25924837, 0.18652526, 0.21595516, 0.27010545,
       0.23240362, 0.3214524 , 0.29013995, 0.22669816, 0.17678784,
       0.18565337, 0.24083074, 0.21480156, 0.24015658, 0.24822103,
       0.20134578, 0.19332459, 0.33538697, 0.24245847, 0.23808982,
       0.23670343, 0.16092742, 0.27237684, 0.22996645, 0.15498116,
       0.23622612, 0.20136976, 0.20188475, 0.35468804, 0.40379754,
       0.26592192, 0.23172724, 0.19943325, 0.15946862, 0.14712584,
       0.20976272, 0.1324057 , 0.16611673, 0.1921724 , 0.16214023,
       0.16966591, 0.19487746, 0.17571992, 0.2001713 , 0.22562974,
       0.22322969, 0.19970707, 0.1341697 , 0.16794026, 0.1914314 ,
       0.2247776 , 0.28213342, 0.18514283, 0.18409889, 0.17680207,
       0.21964233, 0.19522739, 0.22620753, 0.21755384, 0.1621881 ,
       0.20084776, 0.23579002, 0.17986274, 0.17705043, 0.21501

In [26]:
data2013_y2 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2013_y2.csv")
data2013_y2.head(3)

Unnamed: 0  NUID  SATREAD  SATMATH  ACTCUM  CARNIGIE  AVGSALMALE  \
0           1   830      450      450      19        18        7438   
1           2  4829      640      650      28        15       11106   
2           3  4370      480      480      19        18        6942   

   AVGSALWOM  AVGSALTOT  HOUSE    ...      FEEINS  TUITOUT  FEEOUT  FOOTBALL  \
0       6567       7079  0.803    ...        1590    11184    1590       0.0   
1       9149      10170  0.803    ...           0    16398       0       0.0   
2       6216       6557  0.803    ...        1784    13872    1784       0.0   

    TUITPER    SLCTVTY    APPEAL    RSRCHPSTU  HIGHBP  FRACDEGRE  
0  0.300903   0.862019  0.042123   1427.97515     0.0   0.151279  
1  0.061987   0.857143  0.247772  12581.25524    45.9   0.206029  
2  0.298823  50.434783  0.166379    302.61442    40.6   0.121203  

[3 rows x 28 columns]

In [38]:
xtrainy2=pd.DataFrame(data2013_y2.values[:,[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24,25,26,27]])
xtrainy2

0      1     2     3        4       5        6      7      8      9   \
0     450.0  450.0  19.0  18.0   7438.0  6567.0   7079.0  0.803 -0.474  0.908   
1     640.0  650.0  28.0  15.0  11106.0  9149.0  10170.0  0.803 -0.474  0.908   
2     480.0  480.0  19.0  18.0   6942.0  6216.0   6557.0  0.803 -0.474  0.908   
3     620.0  640.0  30.0  16.0  10826.0  8073.0   9605.0  0.803 -0.474  0.908   
4     550.0  540.0  23.0  18.0   7669.0  6582.0   7173.0  0.803 -0.474  0.908   
5     620.0  650.0  30.0  16.0  10201.0  8083.0   9429.0  0.803 -0.474  0.908   
6     630.0  640.0  29.0  21.0   7625.0  7325.0   7513.0  0.803 -0.474  0.908   
7     550.0  540.0  25.0  22.0   4477.0  6347.0   5645.0  0.803 -0.474  0.908   
8     500.0  540.0  24.0  22.0   5774.0  6292.0   6027.0  0.803 -0.474  0.908   
9     550.0  540.0  25.0  24.0   5570.0  5221.0   5512.0  0.803 -0.474  0.908   
10    640.0  600.0  24.0  21.0   5581.0  5700.0   5638.0  0.803 -0.474  0.908   
11    550.0  540.0  22.0  18.0   6688.0  6141.0   6408.0  0.803 -0.474  0.908   
12    590.0  600.0  26.0   1.0   5856.0  6015.0   5909.0  0.803 -0.474  0.908   
13    610.0  680.0  25.0  22.0   5151.0  4900.0   5024.0  0.803 -0.474  0.908   
14    613.0  550.0  26.0  19.0   7433.0  6647.0   7035.0  0.803 -0.474  0.908   
15    565.0  530.0  25.0  18.0   7553.0  6768.0   7152.0  0.803 -0.474  0.908   
16    513.0  510.0  22.0  22.0   5587.0  5035.0   5307.0  0.803 -0.474  0.908   
17    630.0  610.0  28.0  19.0   9091.0  7378.0   8261.0  0.803 -0.474  0.908   
18    550.0  565.0  26.0  16.0   7757.0  6672.0   7212.0  0.803 -0.474  0.908   
19    600.0  600.0  27.0  20.0   6056.0  6057.0   6057.0  0.803 -0.474  0.908   
20    550.0  540.0  25.0  24.0   4602.0  4428.0   4577.0  0.803 -0.474  0.908   
21    450.0  438.0  20.0  21.0   4593.0  4867.0   4743.0  0.803 -0.474  0.908   
22    550.0  540.0  24.0  18.0   6351.0  5582.0   5996.0  0.803 -0.474  0.908   
23    550.0  540.0  25.0  10.0   3317.0  3658.0   3613.0  0.771 -1.411  1.263   
24    600.0  630.0  27.0  15.0  11067.0  9083.0  10320.0  0.771 -1.411  1.263   
25    630.0  650.0  29.0  22.0   8470.0  8052.0   8387.0  0.771 -1.411  1.263   
26    550.0  540.0  25.0  18.0   5444.0  5494.0   5473.0  0.771 -1.411  1.263   
27    580.0  580.0  25.0  16.0   8437.0  7276.0   7863.0  0.771 -1.411  1.263   
28    640.0  600.0  30.0  20.0   4330.0  4169.0   4248.0  0.771 -1.411  1.263   
29    480.0  480.0  27.0  17.0   8041.0  6694.0   7480.0  0.678  0.136  1.123   
...     ...    ...   ...   ...      ...     ...      ...    ...    ...    ...   
1460  550.0  540.0  25.0  -3.0      0.0  4167.0   4167.0 -1.061 -1.387 -0.003   
1461  550.0  540.0  25.0  -3.0      0.0  2633.0   2633.0 -1.308 -1.669  1.541   
1462  550.0  540.0  25.0  -3.0      0.0  6511.0   6511.0  0.843 -0.500  0.917   
1463  550.0  540.0  25.0  -3.0   2750.0     0.0   2750.0 -0.905 -0.998  0.028   
1464  550.0  540.0  25.0  -3.0      0.0  7522.0   7522.0  1.042 -1.077  1.307   
1465  550.0  540.0  25.0  -3.0   2295.0     0.0   2295.0 -1.061 -1.387 -0.003   
1466  550.0  560.0  23.0  -3.0   8687.0  7253.0   7938.0  0.809 -0.772  0.921   
1467  550.0  540.0  25.0  -3.0   5233.0  4975.0   5105.0  0.809 -0.772  0.921   
1468  550.0  540.0  25.0  -3.0   7045.0  6083.0   6875.0 -1.061 -1.387 -0.003   
1469  550.0  540.0  25.0  -3.0   5308.0  5622.0   5405.0 -1.200 -1.701  1.655   
1470  550.0  540.0  25.0  -3.0   6360.0  5876.0   6223.0  0.573 -1.050  0.742   
1471  550.0  540.0  25.0  -3.0   6860.0  6660.0   6794.0 -0.190 -0.931  0.396   
1472  550.0  540.0  25.0  -3.0   5599.0  5823.0   5655.0  0.843 -0.500  0.917   
1473  550.0  540.0  25.0  -3.0   5681.0  5418.0   5606.0  0.760 -0.725  0.916   
1474  550.0  540.0  25.0  -3.0   7322.0  6710.0   7186.0  0.808 -0.736  0.976   
1475  550.0  540.0  25.0  -3.0   6481.0  6025.0   6291.0  0.376 -0.655  0.676   
1476  550.0  540.0  25.0  -3.0   5609.0     0.0   5609.0  0.851 -0.611  0.960   
1477  550.0  540.0  25.0  -3.0   7019.0 

In [39]:
data2013_y2 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2013_y2.csv")
data2013_y2.head(3)
data2013_y2.shape
pred2013_y2 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_13y2.csv")
pred2013_y2.head(3)
pred2013_y2.shape
xtrainy2=pd.DataFrame(data2013_y2.values[:,[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24,25,26,27]])
xtesy2=pd.DataFrame(pred2013_y2.values[:,[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24,25,26,27]])
ytrainy2=pd.DataFrame(data2013_y2.values[:,27])
ytesty2=pd.DataFrame(pred2013_y2.values[:,27])
rfr = RandomForestRegressor().fit(xtrainy2, ytrainy2)
y_mody2=rfr.predict(xtesy2)
y_mody2
#y_mody2=pd.DataFrame(y_mody2)
#y_mody2.to_csv('pred13_y2.csv', index=False, header=False)

array([0.0021085 , 0.0021085 , 0.0021085 , 0.00342826, 0.00165289,
       0.00312036, 0.0021085 , 0.00165289, 0.00082645, 0.00391851,
       0.00641341, 0.00492155, 0.00507055, 0.00341942, 0.00341942,
       0.00442952, 0.0037885 , 0.0083747 , 0.00461495, 0.0051052 ,
       0.00641341, 0.0037885 , 0.00341942, 0.0037885 , 0.0070562 ,
       0.00529062, 0.00461495, 0.00739063, 0.0037885 , 0.00296205,
       0.0051052 , 0.0042441 , 0.00428052, 0.00082645, 0.00406928,
       0.00165113, 0.00064103, 0.00183655, 0.00545022, 0.00545022,
       0.00165113, 0.00064103, 0.00315325, 0.0013167 , 0.0010101 ,
       0.0010101 , 0.00425294, 0.00082645, 0.00474496, 0.00082645,
       0.0010101 , 0.00229215, 0.00229215, 0.00296382, 0.00195195,
       0.00195195, 0.00363773, 0.00457686, 0.00476228, 0.00213737,
       0.00314747, 0.00476228, 0.00509671, 0.00360308, 0.00363773,
       0.00326865, 0.00491129, 0.00296382, 0.00232857, 0.00214315,
       0.00296382, 0.00259298, 0.00213737, 0.00251222, 0.00101

## predict_13_RETPCNT - data2013_y3 - random forest

In [41]:
data2013_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2013_y3.csv")
data2013_y3.head(3)
data2013_y3.shape
pred2013_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_13y3.csv")
pred2013_y3.head(3)
pred2013_y3.shape
xtrainy3=pd.DataFrame(data2013_y3.values[:,1:27])
xtesty3=pd.DataFrame(pred2013_y3.values[:,1:27])
ytrainy3=pd.DataFrame(data2013_y3.values[:,27])
ytesty3=pd.DataFrame(pred2013_y3.values[:,27])
rfr = RandomForestRegressor().fit(xtrainy3, ytrainy3)
y_mody3=rfr.predict(xtesty3)
y_mody3

array([86.2, 11.2,  0. , 33. ,  0. , 28.8, 86.5, 75.5, 84.2, 77.2,  7.3,
       97.6,  0. ,  0. , 92.6,  0. ,  5.6,  0. ,  0. ,  0. , 51.8, 85.8,
       85.9,  0. , 94. , 33.6,  0. , 28. , 72.3, 83.2,  0. ,  7.3, 97.2,
       81.6,  0. , 79.7,  8.1, 38.2, 22.4, 22.4, 85.5, 93.3,  0. ,  0. ,
       33.8,  0. ,  0. , 11.2, 33. , 11.2,  0. , 59.4,  0. , 62. , 85. ,
        7.7, 57.7, 20.5,  0. , 35.8,  0. , 97. , 83.3, 64.7, 74.3,  7.2,
       78.1, 92.8, 74.8,  7.7, 86.2, 87.2,  0. ,  0. ,  0. ,  0. ,  7.5,
        7.2,  6.7,  0. ,  0. ,  0. , 63.6,  0. ,  0. ,  0. , 88.6, 84.8,
        0. , 38.2, 97.5, 20.5, 85.9, 40. , 80. , 85.2, 87.7, 79.9, 93.6,
       88. , 82.4, 78.7,  0. ,  0. , 78.3,  0. ,  0. ,  0. , 38. ,  0. ,
       91.1,  0. , 87.3, 16.8, 69. , 78.5,  6.9,  0. ,  4.4,  0. , 83. ,
       92.2, 62.7, 80.7, 61.1, 91.5,  0. , 32.9,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. , 87.6, 16.8, 82.7, 87.6, 80.5,  0. ,  0. , 20.9,
       11.2, 97.5, 80. , 85.6,  0. , 16.8, 11.2,  0

In [42]:
data2013_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2013_y3.csv")
data2013_y3.head(3)
data2013_y3.shape
pred2013_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_13y3.csv")
pred2013_y3.head(3)
pred2013_y3.shape
xtrainy3=pd.DataFrame(data2013_y3.values[:,2:27])
xtesty3=pd.DataFrame(pred2013_y3.values[:,2:27])
ytrainy3=pd.DataFrame(data2013_y3.values[:,27])
ytesty3=pd.DataFrame(pred2013_y3.values[:,27])
rfr = RandomForestRegressor().fit(xtrainy3, ytrainy3)
y_mody3=rfr.predict(xtesty3)
y_mody3

array([0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 1.6, 1.6, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0.8, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 2.4,
       1.6, 0. , 0. , 0. , 2.4, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.8, 4. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.

## predict_13_RETPCNT - data2013_y3 - bagging regressor

In [6]:
data2013_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2013_y3.csv")
data2013_y3.head(3)
data2013_y3.shape
pred2013_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_13y3.csv")
pred2013_y3.head(3)
pred2013_y3.shape
xtrain_13y3=pd.DataFrame(data2013_y3.values[:,1:27])
xtest_13y3=pd.DataFrame(pred2013_y3.values[:,1:27])
ytrain_13y3=pd.DataFrame(data2013_y3.values[:,27])
ytest_13y3=pd.DataFrame(pred2013_y3.values[:,27])
bingr = BaggingRegressor().fit(xtrain_13y3, ytrain_13y3)
y_mod_13y3 = bingr.predict(xtest_13y3)
y_mod_13y3
#y_mody_13y3=pd.DataFrame(y_mod_13y3)
#y_mody_13y3.to_csv('pred13_y3.csv', index=False, header=False)

array([86.6,  0. ,  0. , 11.6,  0. , 39.6, 85.1, 51.1, 86.8, 75.9,  0. ,
       97.1,  0. ,  0. , 92.7,  0. , 11.2,  0. ,  0. ,  0. , 15.4, 87.7,
       85.1,  7.9, 94.6,  6. ,  0. , 22.4, 54.9, 85. ,  8.2,  0. , 97. ,
       83.4,  0. , 76.2,  0. ,  7. , 22.4, 28. , 85. , 93.1,  0. ,  0. ,
       11.6,  0. ,  0. ,  0. , 15.6,  0. ,  0. , 37.2,  0. , 36.6, 86.8,
        0. , 39. , 13.6,  0. ,  8.1,  7.9, 96.8, 82.5, 41.1, 79.5,  0. ,
       75.7, 93.4, 78.2,  0. , 82.4, 89.9,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. , 66. ,  0. ,  0. ,  9.6, 87.7, 87.2,
        7.9,  7.3, 96.7, 17.3, 88. , 37.6, 79.8, 82.6, 85.7, 79.7, 94.4,
       90.8, 81.4, 76.2,  0. ,  0. , 80.1,  0. ,  0. ,  0. , 16.1,  0. ,
       90.5,  0. , 87.7, 11.2, 69.2, 80.7,  0. ,  0. ,  0. ,  0. , 85. ,
       89. , 38.9, 81.8, 45.5, 90.7,  0. ,  7.9,  0. ,  0. ,  0. ,  7.5,
        0. ,  0. ,  0. , 88.5, 11.2, 84.8, 86.5, 81.3,  7.5,  9.4, 13.2,
       22.4, 97.1, 84.3, 83.1,  0. , 11.2,  0. ,  0

In [22]:
data2013_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2013_y3.csv")
data2013_y3.head(3)
data2013_y3.shape
pred2013_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_13y3.csv")
pred2013_y3.head(3)
pred2013_y3.shape
xtrain_13y3=pd.DataFrame(data2013_y3.values[:,2:27])
xtest_13y3=pd.DataFrame(pred2013_y3.values[:,2:27])
ytrain_13y3=pd.DataFrame(data2013_y3.values[:,27])
ytest_13y3=pd.DataFrame(pred2013_y3.values[:,27])
bingr = BaggingRegressor().fit(xtrain_13y3, ytrain_13y3)
y_mod_13y3 = bingr.predict(xtest_13y3)
y_mod_13y3
y_mody_13y3=pd.DataFrame(y_mod_13y3)
y_mody_13y3.to_csv('pred13_y3.csv', index=False, header=False)

## predict_14_Chgenro - data2014_y1  - random forest

In [49]:
data2014_y1 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2014_y1.csv")
data2014_y1.head(3)
data2014_y1.shape
pred2014_y1 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_14y1.csv")
pred2014_y1.head(3)
pred2014_y1.shape
xtrain_14y1=pd.DataFrame(data2014_y1.values[:,1:30])
xtest_14y1=pd.DataFrame(pred2014_y1.values[:,1:30])
ytrain_14y1=pd.DataFrame(data2014_y1.values[:,30])
ytest_14y1=pd.DataFrame(pred2014_y1.values[:,30])
rfr = RandomForestRegressor().fit(xtrain_14y1, ytrain_14y1)
y_mod_14y1=rfr.predict(xtest_14y1)
y_mod_14y1
y_mod_14y1=pd.DataFrame(y_mod_14y1)
y_mod_14y1.to_csv('pred14_y1.csv', index=False, header=False)

In [17]:
data2014_y1 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2014_y1.csv")
data2014_y1.head(3)
data2014_y1.shape
pred2014_y1 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_14y1.csv")
pred2014_y1.head(3)
pred2014_y1.shape
xtrain_14y1=pd.DataFrame(data2014_y1.values[:,2:30])
xtest_14y1=pd.DataFrame(pred2014_y1.values[:,2:30])
ytrain_14y1=pd.DataFrame(data2014_y1.values[:,30])
ytest_14y1=pd.DataFrame(pred2014_y1.values[:,30])
rfr = RandomForestRegressor().fit(xtrain_14y1, ytrain_14y1)
y_mod_14y1=rfr.predict(xtest_14y1)
y_mod_14y1
y_mod_14y1=pd.DataFrame(y_mod_14y1)
y_mod_14y1.to_csv('pred14_y1.csv', index=False, header=False)

## predict_14_Fracdeg - data2014_y2 - random forest

In [13]:
data2014_y2 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2014_y2.csv")
data2014_y2.head(3)
data2014_y2.shape
pred2014_y2 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_14y2.csv")
pred2014_y2.head(3)
pred2014_y2.shape
xtrain_14y2=pd.DataFrame(data2014_y2.values[:,1:30])
xtest_14y2=pd.DataFrame(pred2014_y2.values[:,1:30])
ytrain_14y2=pd.DataFrame(data2014_y2.values[:,30])
ytest_14y2=pd.DataFrame(pred2014_y2.values[:,30])
rfr = RandomForestRegressor().fit(xtrain_14y2, ytrain_14y2)
y_mod_14y2=rfr.predict(xtest_14y2)
y_mod_14y2

array([0.21681499, 0.14584364, 0.15731195, 0.19295019, 0.19916164,
       0.50622218, 0.20078994, 0.18607466, 0.19020126, 0.18723045,
       0.3430509 , 0.27075967, 0.19572571, 0.21738633, 0.25958227,
       0.22832434, 0.30525597, 0.22871216, 0.163932  , 0.24414953,
       0.22940383, 0.22795641, 0.23493079, 0.2460004 , 0.26112404,
       0.223119  , 0.18428466, 0.45851646, 0.23677109, 0.21676609,
       0.23654991, 0.17745294, 0.27969656, 0.25026456, 0.14277686,
       0.19936132, 0.1891313 , 0.17953634, 0.60587096, 0.58944526,
       0.25169939, 0.22903744, 0.16781726, 0.17577196, 0.18902153,
       0.2191469 , 0.1440068 , 0.17860848, 0.18464839, 0.18873503,
       0.20670731, 0.19767281, 0.1619824 , 0.18108446, 0.20435443,
       0.19973393, 0.18125671, 0.18332953, 0.17386824, 0.20182288,
       0.23984986, 0.29151625, 0.21903892, 0.17220323, 0.18928352,
       0.24631206, 0.20049874, 0.24344551, 0.18992169, 0.20162137,
       0.19332745, 0.2022874 , 0.18678208, 0.18996872, 0.19738

## predict_14_Fracdeg - data2014_y2 - bagging regressor

In [10]:
data2014_y2 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2014_y2.csv")
data2014_y2.head(3)
data2014_y2.shape
pred2014_y2 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_14y2.csv")
pred2014_y2.head(3)
pred2014_y2.shape
xtrain_14y2=pd.DataFrame(data2014_y2.values[:,1:30])
xtest_14y2=pd.DataFrame(pred2014_y2.values[:,1:30])
ytrain_14y2=pd.DataFrame(data2014_y2.values[:,30])
ytest_14y2=pd.DataFrame(pred2014_y2.values[:,30])
bingr = BaggingRegressor().fit(xtrain_14y2, ytrain_14y2)
y_mod_14y2_1=bingr.predict(xtest_14y2)
y_mod_14y2_1
y_mod_14y2_1=pd.DataFrame(y_mod_14y2_1)
y_mod_14y2_1.to_csv('pred14_y2.csv', index=False, header=False)

In [14]:
data2014_y2 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2014_y2.csv")
data2014_y2.head(3)
data2014_y2.shape
pred2014_y2 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_14y2.csv")
pred2014_y2.head(3)
pred2014_y2.shape
xtrain_14y2=pd.DataFrame(data2014_y2.values[:,2:30])
xtest_14y2=pd.DataFrame(pred2014_y2.values[:,2:30])
ytrain_14y2=pd.DataFrame(data2014_y2.values[:,30])
ytest_14y2=pd.DataFrame(pred2014_y2.values[:,30])
bingr = BaggingRegressor().fit(xtrain_14y2, ytrain_14y2)
y_mod_14y2_1=bingr.predict(xtest_14y2)
y_mod_14y2_1
y_mod_14y2_1=pd.DataFrame(y_mod_14y2_1)
y_mod_14y2_1.to_csv('pred14_y2.csv', index=False, header=False)

## predic_14_RETPCNT - data2014_y3 - random forest

In [51]:
data2014_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2014_y3.csv")
data2014_y3.head(3)
data2014_y3.shape
pred2014_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_14y3.csv")
pred2014_y3.head(3)
pred2014_y3.shape
xtrain_14y3=pd.DataFrame(data2014_y3.values[:,1:30])
xtest_14y3=pd.DataFrame(pred2014_y3.values[:,1:30])
ytrain_14y3=pd.DataFrame(data2014_y3.values[:,30])
ytest_14y3=pd.DataFrame(pred2014_y3.values[:,30])
rfr = RandomForestRegressor().fit(xtrain_14y3, ytrain_14y3)
y_mod_14y3=rfr.predict(xtest_14y3)
y_mod_14y3
y_mod_14y3=pd.DataFrame(y_mod_14y3)
y_mod_14y3.to_csv('pred14_y3.csv', index=False, header=False)

In [23]:
data2014_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2014_y3.csv")
data2014_y3.head(3)
data2014_y3.shape
pred2014_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_14y3.csv")
pred2014_y3.head(3)
pred2014_y3.shape
xtrain_14y3=pd.DataFrame(data2014_y3.values[:,2:30])
xtest_14y3=pd.DataFrame(pred2014_y3.values[:,2:30])
ytrain_14y3=pd.DataFrame(data2014_y3.values[:,30])
ytest_14y3=pd.DataFrame(pred2014_y3.values[:,30])
rfr = RandomForestRegressor().fit(xtrain_14y3, ytrain_14y3)
y_mod_14y3=rfr.predict(xtest_14y3)
y_mod_14y3
y_mod_14y3=pd.DataFrame(y_mod_14y3)
y_mod_14y3.to_csv('pred14_y3.csv', index=False, header=False)

## predic_15_Chgenrol - data2015_y1 - random forest

In [52]:
data2015_y1 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2015_y1.csv")
data2015_y1.head(3)
data2015_y1.shape
pred2015_y1 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_15y1.csv")
pred2015_y1.head(3)
pred2015_y1.shape
xtrain_15y1=pd.DataFrame(data2015_y1.values[:,1:27])
xtest_15y1=pd.DataFrame(pred2015_y1.values[:,1:27])
ytrain_15y1=pd.DataFrame(data2015_y1.values[:,27])
ytest_15y2=pd.DataFrame(pred2015_y1.values[:,27])
rfr = RandomForestRegressor().fit(xtrain_15y1, ytrain_15y1)
y_mod_15y1=rfr.predict(xtest_15y1)
y_mod_15y1
y_mod_15y1=pd.DataFrame(y_mod_15y1)
y_mod_15y1.to_csv('pred15_y1.csv', index=False, header=False)

In [18]:
data2015_y1 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2015_y1.csv")
data2015_y1.head(3)
data2015_y1.shape
pred2015_y1 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_15y1.csv")
pred2015_y1.head(3)
pred2015_y1.shape
xtrain_15y1=pd.DataFrame(data2015_y1.values[:,2:27])
xtest_15y1=pd.DataFrame(pred2015_y1.values[:,2:27])
ytrain_15y1=pd.DataFrame(data2015_y1.values[:,27])
ytest_15y2=pd.DataFrame(pred2015_y1.values[:,27])
rfr = RandomForestRegressor().fit(xtrain_15y1, ytrain_15y1)
y_mod_15y1=rfr.predict(xtest_15y1)
y_mod_15y1
y_mod_15y1=pd.DataFrame(y_mod_15y1)
y_mod_15y1.to_csv('pred15_y1.csv', index=False, header=False)

## predic_15_FRANC - data2015_y2 - random forest

In [19]:
data2015_y2 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2015_y2.csv")
data2015_y2.head(3)
data2015_y2.shape
pred2015_y2 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_15y2.csv")
pred2015_y2.head(3)
pred2015_y2.shape
xtrain_15y2=pd.DataFrame(data2015_y2.values[:,1:27])
xtest_15y2=pd.DataFrame(pred2015_y2.values[:,1:27])
ytrain_15y2=pd.DataFrame(data2015_y2.values[:,27])
ytest_15y2=pd.DataFrame(pred2015_y2.values[:,27])
rfr = RandomForestRegressor().fit(xtrain_15y2, ytrain_15y2)
y_mod_15y2=rfr.predict(xtest_15y2)
y_mod_15y2

array([0.2042984 , 0.13037048, 0.17045888, 0.15699265, 0.21437573,
       0.47179022, 0.21562399, 0.20538084, 0.21237699, 0.18572644,
       0.25171926, 0.26219824, 0.17877383, 0.19271979, 0.24917366,
       0.21470626, 0.25632733, 0.3214088 , 0.23340398, 0.19755978,
       0.26209793, 0.25963705, 0.20609328, 0.26983576, 0.23547269,
       0.20906157, 0.18836425, 0.28466339, 0.22299197, 0.24031134,
       0.23726747, 0.18791667, 0.26995322, 0.22959133, 0.17015922,
       0.20867531, 0.19262292, 0.19383884, 0.26708033, 0.33122183,
       0.24030924, 0.23754411, 0.17919501, 0.15952027, 0.17312803,
       0.22594934, 0.14398364, 0.14447908, 0.18189687, 0.17106881,
       0.22032186, 0.19971385, 0.1597488 , 0.18222397, 0.21677957,
       0.2071422 , 0.22090784, 0.19501844, 0.17700939, 0.20561432,
       0.23502079, 0.27543098, 0.22117257, 0.1732575 , 0.19194211,
       0.22238296, 0.21845847, 0.22229722, 0.19587801, 0.18532036,
       0.22214339, 0.21732298, 0.19639167, 0.25414084, 0.17953

## predic_15_fracde - data2015_y2 - bagging regresorr

In [53]:
data2015_y2 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2015_y2.csv")
data2015_y2.head(3)
data2015_y2.shape
pred2015_y2 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_15y2.csv")
pred2015_y2.head(3)
pred2015_y2.shape
xtrain_15y2=pd.DataFrame(data2015_y2.values[:,1:27])
xtest_15y2=pd.DataFrame(pred2015_y2.values[:,1:27])
ytrain_15y2=pd.DataFrame(data2015_y2.values[:,27])
ytest_15y2=pd.DataFrame(pred2015_y2.values[:,27])
bingr = BaggingRegressor().fit(xtrain_15y2, ytrain_15y2)
y_mod_15y2_1=bingr.predict(xtest_15y2)
y_mod_15y2_1
y_mod_15y2_1=pd.DataFrame(y_mod_15y2_1)
y_mod_15y2_1.to_csv('pred15_y2.csv', index=False, header=False)

In [15]:
data2015_y2 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2015_y2.csv")
data2015_y2.head(3)
data2015_y2.shape
pred2015_y2 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_15y2.csv")
pred2015_y2.head(3)
pred2015_y2.shape
xtrain_15y2=pd.DataFrame(data2015_y2.values[:,2:27])
xtest_15y2=pd.DataFrame(pred2015_y2.values[:,2:27])
ytrain_15y2=pd.DataFrame(data2015_y2.values[:,27])
ytest_15y2=pd.DataFrame(pred2015_y2.values[:,27])
bingr = BaggingRegressor().fit(xtrain_15y2, ytrain_15y2)
y_mod_15y2_1=bingr.predict(xtest_15y2)
y_mod_15y2_1
y_mod_15y2_1=pd.DataFrame(y_mod_15y2_1)
y_mod_15y2_1.to_csv('pred15_y2.csv', index=False, header=False)

## predic_15_retpcnt - data2015_y3 - random forest

In [21]:
data2015_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2015_y3.csv")
data2015_y3.head(3)
data2015_y3.shape
pred2015_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_15y3.csv")
pred2015_y3.head(3)
pred2015_y3.shape
xtrain_15y3=pd.DataFrame(data2015_y3.values[:,1:27])
xtest_15y3=pd.DataFrame(pred2015_y3.values[:,1:27])
ytrain_15y3=pd.DataFrame(data2015_y3.values[:,27])
ytest_15y3=pd.DataFrame(pred2015_y3.values[:,27])
rfr = RandomForestRegressor().fit(xtrain_15y3, ytrain_15y3)
y_mod_15y3=rfr.predict(xtest_15y3)
y_mod_15y3

array([88.6, 21.2, 58.3, 53.6, 60.2, 67.2, 84.2, 59.7, 82.8, 60. , 38.5,
       96.7, 79.3, 76.6, 91.7, 62. , 53.4, 38.4, 77.3, 52.9, 80. , 79. ,
       82.6, 84.4, 93.9, 56. , 77.4, 49.2, 68.7, 83.8, 86.5, 75.3, 97.8,
       83. , 30.1, 79.6, 73.3, 58.8, 25.1, 28.3, 87.3, 91.9, 29.9, 31.1,
       61.7, 28.5, 24.4, 46.8, 22. , 73.3, 23.7, 79.5, 25.1, 34.3, 87.2,
       74.8, 62.5, 60.5, 32.4, 61.6, 86. , 96.8, 79.3, 78.3, 61.4, 66.1,
       75.3, 91.4, 62.2, 61.7, 74.5, 87.9, 63.2, 37.4, 56.8, 34.7, 50.3,
       47.7, 39.4, 58.1, 35.9, 40.4, 65.4, 45.7, 48. , 84.2, 91.3, 72.8,
       73.5, 81.7, 98.2, 94.2, 83.1, 76.5, 74.6, 87.2, 86.8, 75.1, 93.5,
       88.7, 82.2, 82. , 75.1, 36.6, 84.8, 68.8, 75. , 72.4, 64.8, 48.6,
       91. , 28.8, 85.5, 42.9, 33.8, 84.1, 49.9, 65.1, 50.7, 45. , 87.5,
       86.6, 77. , 74.5, 44.7, 85.3, 69.1, 34. , 57.8, 61.2, 39.5, 44.2,
       76.9, 76.3, 76.1, 86.6, 22.1, 80.5, 87.1, 61. , 77.3, 91.2, 65.3,
       29. , 97.4, 81.8, 86.3, 37.9, 34. , 42.9, 40

## predic_15_retpcnt- data2015_y3 - bagging regresorr

In [54]:
data2015_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2015_y3.csv")
data2015_y3.head(3)
data2015_y3.shape
pred2015_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_15y3.csv")
pred2015_y3.head(3)
pred2015_y3.shape
xtrain_15y3=pd.DataFrame(data2015_y3.values[:,1:27])
xtest_15y3=pd.DataFrame(pred2015_y3.values[:,1:27])
ytrain_15y3=pd.DataFrame(data2015_y3.values[:,27])
ytest_15y3=pd.DataFrame(pred2015_y3.values[:,27])
bingr = BaggingRegressor().fit(xtrain_15y3, ytrain_15y3)
y_mod_15y3_1=bingr.predict(xtest_15y3)
y_mod_15y3_1
y_mod_15y3_1=pd.DataFrame(y_mod_15y3_1)
y_mod_15y3_1.to_csv('pred15_y3.csv', index=False, header=False)

In [24]:
data2015_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2015_y3.csv")
data2015_y3.head(3)
data2015_y3.shape
pred2015_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_15y3.csv")
pred2015_y3.head(3)
pred2015_y3.shape
xtrain_15y3=pd.DataFrame(data2015_y3.values[:,2:27])
xtest_15y3=pd.DataFrame(pred2015_y3.values[:,2:27])
ytrain_15y3=pd.DataFrame(data2015_y3.values[:,27])
ytest_15y3=pd.DataFrame(pred2015_y3.values[:,27])
bingr = BaggingRegressor().fit(xtrain_15y3, ytrain_15y3)
y_mod_15y3_1=bingr.predict(xtest_15y3)
y_mod_15y3_1
y_mod_15y3_1=pd.DataFrame(y_mod_15y3_1)
y_mod_15y3_1.to_csv('pred15_y3.csv', index=False, header=False)

## predic_16_Chgenrol - data2016_y1 - random forest

In [55]:
data2016_y1 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2016_y1.csv")
data2016_y1.head(3)
data2016_y1.shape
pred2016_y1 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_16y1.csv")
pred2016_y1.head(3)
pred2016_y1.shape
xtrain_16y1=pd.DataFrame(data2016_y1.values[:,1:30])
xtest_16y1=pd.DataFrame(pred2016_y1.values[:,1:30])
ytrain_16y1=pd.DataFrame(data2016_y1.values[:,30])
ytest_16y1=pd.DataFrame(pred2016_y1.values[:,30])
rfr = RandomForestRegressor().fit(xtrain_16y1, ytrain_16y1)
y_mod_16y1=rfr.predict(xtest_16y1)
y_mod_16y1
y_mod_16y1=pd.DataFrame(y_mod_16y1)
y_mod_16y1.to_csv('pred16_y1.csv', index=False, header=False)

In [19]:
data2016_y1 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2016_y1.csv")
data2016_y1.head(3)
data2016_y1.shape
pred2016_y1 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_16y1.csv")
pred2016_y1.head(3)
pred2016_y1.shape
xtrain_16y1=pd.DataFrame(data2016_y1.values[:,2:30])
xtest_16y1=pd.DataFrame(pred2016_y1.values[:,2:30])
ytrain_16y1=pd.DataFrame(data2016_y1.values[:,30])
ytest_16y1=pd.DataFrame(pred2016_y1.values[:,30])
rfr = RandomForestRegressor().fit(xtrain_16y1, ytrain_16y1)
y_mod_16y1=rfr.predict(xtest_16y1)
y_mod_16y1
y_mod_16y1=pd.DataFrame(y_mod_16y1)
y_mod_16y1.to_csv('pred16_y1.csv', index=False, header=False)

## predic_16_fracdegre - data2016_y2 - random forest

In [26]:
data2016_y2 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2016_y1.csv")
data2016_y2.head(3)
data2016_y2.shape
pred2016_y2 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_16y1.csv")
pred2016_y2.head(3)
pred2016_y2.shape
xtrain_16y2=pd.DataFrame(data2016_y2.values[:,1:30])
xtest_16y2=pd.DataFrame(pred2016_y2.values[:,1:30])
ytrain_16y2=pd.DataFrame(data2016_y2.values[:,30])
ytest_16y2=pd.DataFrame(pred2016_y2.values[:,30])
rfr = RandomForestRegressor().fit(xtrain_16y2, ytrain_16y2)
y_mod_16y2=rfr.predict(xtest_16y2)
y_mod_16y2

array([1.00259816, 1.01795324, 1.03850404, 0.95297124, 0.91808606,
       1.01773419, 1.08374879, 1.13768541, 1.03072891, 1.03671494,
       0.98056431, 0.81408   , 1.02002812, 1.08898405, 1.02789765,
       1.08509958, 1.14302848, 1.03662915, 1.02843536, 0.98210339,
       0.84402285, 0.99390783, 1.12106909, 0.95362905, 1.01436194,
       0.97825889, 1.06622248, 0.95295551, 0.98557532, 1.0109104 ,
       0.98512795, 0.97290932, 0.94431247, 0.93688728, 1.08251148,
       0.98212679, 1.08242834, 1.02180779, 0.96858141, 1.04915108,
       1.02398875, 0.99129572, 1.10804864, 1.06982296, 1.06307808,
       0.9653006 , 1.00595637, 0.95148243, 1.00434839, 0.93126264,
       1.089131  , 1.03081442, 1.0178952 , 1.0181789 , 1.0133675 ,
       0.97911518, 1.01930111, 1.08150504, 1.00593301, 0.97392486,
       1.02878817, 1.01246388, 0.97455238, 1.01391817, 1.01564724,
       1.01539104, 0.94569501, 0.99973508, 1.0079019 , 0.83232368,
       0.98822676, 0.96995038, 1.05204857, 0.96650326, 1.04625

## predic_16_fracdegre - data2016_y2 - bagging

In [56]:
data2016_y2 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2016_y1.csv")
data2016_y2.head(3)
data2016_y2.shape
pred2016_y2 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_16y1.csv")
pred2016_y2.head(3)
pred2016_y2.shape
xtrain_16y2=pd.DataFrame(data2016_y2.values[:,1:30])
xtest_16y2=pd.DataFrame(pred2016_y2.values[:,1:30])
ytrain_16y2=pd.DataFrame(data2016_y2.values[:,30])
ytest_16y2=pd.DataFrame(pred2016_y2.values[:,30])
bingr = BaggingRegressor().fit(xtrain_16y2, ytrain_16y2)
y_mod_16y2_1=bingr.predict(xtest_16y2)
y_mod_16y2_1
y_mod_16y2_1=pd.DataFrame(y_mod_16y2_1)
y_mod_16y2_1.to_csv('pred16_y2.csv', index=False, header=False)

In [16]:
data2016_y2 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2016_y1.csv")
data2016_y2.head(3)
data2016_y2.shape
pred2016_y2 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_16y1.csv")
pred2016_y2.head(3)
pred2016_y2.shape
xtrain_16y2=pd.DataFrame(data2016_y2.values[:,2:30])
xtest_16y2=pd.DataFrame(pred2016_y2.values[:,2:30])
ytrain_16y2=pd.DataFrame(data2016_y2.values[:,30])
ytest_16y2=pd.DataFrame(pred2016_y2.values[:,30])
bingr = BaggingRegressor().fit(xtrain_16y2, ytrain_16y2)
y_mod_16y2_1=bingr.predict(xtest_16y2)
y_mod_16y2_1
y_mod_16y2_1=pd.DataFrame(y_mod_16y2_1)
y_mod_16y2_1.to_csv('pred16_y2.csv', index=False, header=False)

## predic_16_fracdegre - data2016_y3 - random forest

In [57]:
data2016_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2016_y3.csv")
data2016_y3.head(3)
data2016_y3.shape
pred2016_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_16y3.csv")
pred2016_y3.head(3)
pred2016_y3.shape
xtrain_16y3=pd.DataFrame(data2016_y3.values[:,1:30])
xtest_16y3=pd.DataFrame(pred2016_y3.values[:,1:30])
ytrain_16y3=pd.DataFrame(data2016_y3.values[:,30])
ytest_16y3=pd.DataFrame(pred2016_y3.values[:,30])
rfr = RandomForestRegressor().fit(xtrain_16y3, ytrain_16y3)
y_mod_16y3=rfr.predict(xtest_16y3)
y_mod_16y3
y_mod_16y3=pd.DataFrame(y_mod_16y3)
y_mod_16y3.to_csv('pred16_y3.csv', index=False, header=False)

In [25]:
data2016_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2016_y3.csv")
data2016_y3.head(3)
data2016_y3.shape
pred2016_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_16y3.csv")
pred2016_y3.head(3)
pred2016_y3.shape
xtrain_16y3=pd.DataFrame(data2016_y3.values[:,2:30])
xtest_16y3=pd.DataFrame(pred2016_y3.values[:,2:30])
ytrain_16y3=pd.DataFrame(data2016_y3.values[:,30])
ytest_16y3=pd.DataFrame(pred2016_y3.values[:,30])
rfr = RandomForestRegressor().fit(xtrain_16y3, ytrain_16y3)
y_mod_16y3=rfr.predict(xtest_16y3)
y_mod_16y3
y_mod_16y3=pd.DataFrame(y_mod_16y3)
y_mod_16y3.to_csv('pred16_y3.csv', index=False, header=False)

## predic_16_fracdegre - data2016_y3 - bagging regressor

In [32]:
data2016_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/data2016_y3.csv")
data2016_y3.head(3)
data2016_y3.shape
pred2016_y3 = pd.read_csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Imputed/prediction_16y3.csv")
pred2016_y3.head(3)
pred2016_y3.shape
xtrain_16y3=pd.DataFrame(data2016_y3.values[:,1:30])
xtest_16y3=pd.DataFrame(pred2016_y3.values[:,1:30])
ytrain_16y3=pd.DataFrame(data2016_y3.values[:,30])
ytest_16y3=pd.DataFrame(pred2016_y3.values[:,30])
bingr = BaggingRegressor().fit(xtrain_16y3, ytrain_16y3)
y_mod_16y3_1=bingr.predict(xtest_16y3)
y_mod_16y3_1

array([88.6, 23.1, 59.8, 35.3, 16.3, 25.9, 70.4, 33.7, 79.2, 64.4, 23.2,
       86.5, 53.9, 53.8, 90. , 64.1, 26.9, 18.5, 38.6, 26.7, 46.5, 86.2,
       77.8, 71.8, 92.5, 39.3, 46. , 25.7, 63.1, 65.4, 68.9, 77.2, 96.4,
       65.7, 25. , 47.6, 75. , 61.8, 21.2, 20.4, 85.5, 89.3, 21.6, 33.4,
       32.3, 33. , 33.7, 37.3, 34.9, 55. , 24. , 53.2, 30.3, 56.5, 74.8,
       69.9, 27.6, 31.9, 28.1, 62.1, 57.8, 85.9, 49.9, 57.2, 63.7, 70.4,
       76.8, 88.9, 60. , 62.6, 73.9, 66. , 64.4, 25.7, 56.9, 28.4, 35.7,
       58.3, 27.2, 60.1, 26.1, 24.6, 34.9, 31.1, 35.3, 67. , 89.3, 82.8,
       51.5, 53.8, 86.3, 69.3, 67.5, 75.5, 70.7, 85.2, 75.4, 70.6, 93.1,
       77.8, 79.4, 53. , 68.1, 25.2, 82.6, 53.5, 74.6, 51.2, 59.9, 13.6,
       82.6, 51. , 86.9, 35.9, 27.7, 51.9, 50. , 49.5, 30.1, 51. , 77.9,
       90.8, 60.7, 71.9, 54.4, 86.2, 60.3, 61.2, 63.1, 59.1, 57.9, 21.7,
       59.6, 61.3, 59.7, 86.7, 23.1, 80.6, 66. , 63.2, 42.7, 60.4, 25.6,
       16.5, 86.5, 59.7, 87.9, 25.9, 11.9, 58. , 19